names = [{'name': 'Pralhad', 'age': 17},
 {'name': 'Bhavnesh', 'age': 25},
 {'name': 'Bhavnesh', 'age': 20},
 {'name': 'Anoop', 'age': 19},
 {'name': 'Rishabh', 'age': 24},
 {'name': 'Rishabh', 'age': 24},
 {'name': 'Bhavnesh', 'age': 18},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Anoop', 'age': 16},
 {'name': 'Bhavnesh', 'age': 21},
 {'name': 'Bhavnesh', 'age': 21},
 {'name': 'Anoop', 'age': 19},
 {'name': 'Anoop', 'age': 23},
 {'name': 'Anoop', 'age': 16},
 {'name': 'Rishabh', 'age': 17},
 {'name': 'Bhavnesh', 'age': 17},
 {'name': 'Rishabh', 'age': 15},
 {'name': 'Anurag', 'age': 19},
 {'name': 'Bhavnesh', 'age': 20},
 {'name': 'Rishabh', 'age': 24},
 {'name': 'Anoop', 'age': 23},
 {'name': 'Anurag', 'age': 25},
 {'name': 'Bhavnesh', 'age': 19},
 {'name': 'Pralhad', 'age': 18},
 {'name': 'Anoop', 'age': 16},
 {'name': 'Anoop', 'age': 25},
 {'name': 'Rishabh', 'age': 23},
 {'name': 'Anoop', 'age': 23},
 {'name': 'Anurag', 'age': 23},
 {'name': 'Bhavnesh', 'age': 22},
 {'name': 'Anurag', 'age': 20},
 {'name': 'Rishabh', 'age': 20},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Pralhad', 'age': 16},
 {'name': 'Rishabh', 'age': 23},
 {'name': 'Anoop', 'age': 16},
 {'name': 'Rishabh', 'age': 16},
 {'name': 'Pralhad', 'age': 23},
 {'name': 'Rishabh', 'age': 19},
 {'name': 'Pralhad', 'age': 20},
 {'name': 'Anoop', 'age': 22},
 {'name': 'Rishabh', 'age': 16},
 {'name': 'Rishabh', 'age': 15},
 {'name': 'Pralhad', 'age': 15},
 {'name': 'Pralhad', 'age': 20},
 {'name': 'Pralhad', 'age': 18},
 {'name': 'Rishabh', 'age': 18},
 {'name': 'Anoop', 'age': 15},
 {'name': 'Anoop', 'age': 16},
 {'name': 'Anoop', 'age': 19},
 {'name': 'Anurag', 'age': 20},
 {'name': 'Rishabh', 'age': 17},
 {'name': 'Bhavnesh', 'age': 17},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Rishabh', 'age': 18},
 {'name': 'Pralhad', 'age': 23},
 {'name': 'Anurag', 'age': 16},
 {'name': 'Pralhad', 'age': 21},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Anurag', 'age': 16},
 {'name': 'Rishabh', 'age': 22},
 {'name': 'Bhavnesh', 'age': 16},
 {'name': 'Pralhad', 'age': 20},
 {'name': 'Bhavnesh', 'age': 17},
 {'name': 'Pralhad', 'age': 22},
 {'name': 'Bhavnesh', 'age': 21},
 {'name': 'Anurag', 'age': 20},
 {'name': 'Pralhad', 'age': 16},
 {'name': 'Rishabh', 'age': 24},
 {'name': 'Pralhad', 'age': 18},
 {'name': 'Rishabh', 'age': 23},
 {'name': 'Rishabh', 'age': 19},
 {'name': 'Rishabh', 'age': 21},
 {'name': 'Pralhad', 'age': 23},
 {'name': 'Rishabh', 'age': 15},
 {'name': 'Bhavnesh', 'age': 17},
 {'name': 'Anurag', 'age': 17},
 {'name': 'Pralhad', 'age': 24},
 {'name': 'Anurag', 'age': 15},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Bhavnesh', 'age': 24},
 {'name': 'Anoop', 'age': 23},
 {'name': 'Pralhad', 'age': 25},
 {'name': 'Bhavnesh', 'age': 22}]
# O/P:-['Pralhad', 'Bhavnesh', 'Anoop', 'Rishabh']
list1=[]
list2=[]
for i in names:
    a=(i["name"])
    list1.append(a)
    if a not in list2:
        list2.append(a)
print(list2)